linkervision/visionai-data-format

visionai_data_format/schemas/common.py, visionai_data_format/utils/checker.py
Add checkers for each format, which can be used anywhere e.g. airflow DAGs, celery tasks, etc.
```python
checker = get_format_checker(AnnotationFormat.KITTI)
print(
checker(dataset_type=dataset_type, sequential=sequential, ..., pcd_type=pcd_type).valid
)
```
- [AB#11386](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/11386)
- Add two files.
=> feat(checker): add format checkers

setup.py, visionai_data_format/schemas/visionai_schema.py
modify default value of schema since we need the keys even the values are empty
- Modify default value for `Optional` fields
=> fix(python): redefine default value of `VisionAI` schema

setup.py, visionai_data_format/schemas/visionai_schema.py
as mentioned. we need to assign metadata value such as `schema_version` automatically.
- assign current schema version default value
=> fix(python): assign missing metadata default value

setup.py, visionai_data_format/schemas/visionai_schema.py
as mentioned. wrong `default_factory` type for `frame_intervals` field
- assign with right default value
=> fix(python): fix wrong default_factory value

visionai_data_format/Readme.md, visionai_data_format/coco_to_vai.py, visionai_data_format/utils/common.py, visionai_data_format/vai_to_coco.py
add flag to enable user to copy image while converting
- [AB#]()
- add `--copy-image` flag for user to be enable to copy the image files while converting
- fix generated visionai format filename to `objects.json`
- add log
- it should work
with `--copy-image` enabled :
without `--copy-image` :
=> fix(python): add copy image option while converting(coco format)

setup.py, visionai_data_format/schemas/bdd_schema.py
as mentioned. we need `frameLabel` to sent dataverse project tag to autolabel platform
- add `frameLabel` field to BDD schema
=> feat(python): add frameLabel in BDD schema

setup.py, tests/test_schemas.py, visionai_data_format/schemas/visionai_schema.py
as mentioned, adding fields for new semantic segmentation format.
[AB#13126](https://dev.azure.com/linkerengineer/Dataverse/_sprints/taskboard/Dataverse%20Team/Dataverse/Sprint%2031%20-%20Pixel%20wise%20smantic%20segmetation?workitem=13126)
- defined [spec ](https://linkervision.getoutline.com/doc/tags-nsxeVqk0KP)
- add `tags` under visionai
- add `binary` model for object related value
- update to newer version number
it should work, could validate our sample [data](https://portal.azure.com/#view/Microsoft_Azure_Storage/ContainerMenuBlade/~/overview/storageAccountId/%2Fsubscriptions%2F091725d9-aeba-4638-8faf-d0e81a03a93d%2FresourceGroups%2Frg-observteam-dev-001%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Fhelenmlopsstorageqatest/path/vainewformat/etag/%220x8DACEB6E744A51D%22/defaul …
=> feat(python): add new semantic format related fields

setup.py, visionai_data_format/utils/validator.py
- Remove indent since the output objects.json is too large
=> fix(python): fix save json indent

conftest.py, tests/test_data/fake_objects_data.json, tests/test_data/fake_raw_data.json, tests/test_data/generated_objects_data.json, tests/test_data/generated_raw_data.json, tests/test_schemas.py, visionai_data_format/schemas/visionai_schema.py
modify default values of visionai fields except of `objects` and `contexts` related fields.
[AB#13467](https://dev.azure.com/linkerengineer/Dataverse/_sprints/taskboard/Dataverse%20Team/Dataverse/Sprint%2033%20-%20VisionAI%20Fomat%20Refinement?workitem=13467)
- change fields default value
- adding validation for fields
- modify test behaviour
Mainly changes `visionai_data_format/schemas/visionai_schema.py`, `tests/test_schemas.py`, and `conftest.py` files.
it should work. Will be merged to `feat/refactor-visionai-schema`, since we will update `contexts` and `objects` related in the next PR
=> fix(python): update visionai fields default value

tests/test_data/fake_objects_data.json, tests/test_data/generated_objects_data.json, visionai_data_format/schemas/visionai_schema.py
update contexts and objects schema required fields and validation logic.[AB#13588](https://dev.azure.com/linkerengineer/Dataverse/_sprints/taskboard/Dataverse%20Team/Dataverse/Sprint%2033%20-%20VisionAI%20Fomat%20Refinement?workitem=13588)
- change required fields condition based on newest format version
- add data pointer with data relationship validation
- separate allowed object type in static and dynamic attributes ( `static` attribute can't contains `bbox`, `cuboid`,`poly2d`,`point2d`, and `binary`)
- remove `coordinate_systems` from `objects` under `frames`
it should work
- object_data_pointer empty dict will raise error
- context_data/object_data empty dict will raise error
- object_data_pointer missing static object_data information will raise error
- raise error if context/object …
=> feat(python): update contexts and objects schema

tests/test_data/fake_objects_data.json, tests/test_data/generated_objects_data.json, visionai_data_format/coco_to_vai.py, visionai_data_format/schemas/visionai_schema.py, visionai_data_format/utils/converter.py
modify visionai schema to newer structure.
- separate `object_data` and `context_data` with dynamic and static version. Only dynamic `object_data` and `context_data` should contains `stream` attribute
- remove `coordinate_system` from dynamic `object_data` and `context_data`.
- rename `number` with `num`
- relocate some basemodel
=> fix(python): modify visionai schema structure

setup.py, tests/test_validators.py, visionai_data_format/schemas/common.py, visionai_data_format/schemas/utils/validators.py, visionai_data_format/schemas/visionai_schema.py
fix visionai-data-format from missing attributes and wrong logic of validation.
[AB#13919](https://dev.azure.com/linkerengineer/Dataverse/_sprints/taskboard/Dataverse%20Team/Dataverse/Sprint%2035%20-%20Data%20Query%20Logic?workitem=13919)
- add `confidence_score` field for dynamic `context` objects
- remove unused replacement of attribute's name, since we let the user build the project ontology with our ontology. ( `option` in dataverse equals with `vec` attribute. we don't need to replace it anymore since we have our own ontology)
- allow all basemodel to exclude none value automatically when calling `.dict()` or `.json()` function 
it should work. Dataverse could import dataset normally.
`.dict()`
`.json()`
=> fix(python): fix wrong and missing visionai and ontology definition 

setup.py, visionai_data_format/coco_to_vai.py, visionai_data_format/utils/converter.py
Modify `objects` retrieval method in case the `Frames` attribute doesn't contains `objects` key information.
Bug found by @yihsuan123 
[AB#14017](https://dev.azure.com/linkerengineer/Dataverse/_sprints/taskboard/Dataverse%20Team/Dataverse/Sprint%2035%20-%20Data%20Query%20Logic?workitem=14017)
- add validation to check whether current frame contains objects attribute with `getattribute`
it should work,  could access frame in case there is not `objects` attribute
=> fix(python): modify retrieve object data method from frames

README.md, setup.py, visionai_data_format/utils/converter.py, visionai_data_format/vai_to_bdd.py
- The bdd converter need to be modified as the new version of VisionAI format have annotation folder for groundtruth/models.
- Previous version does not consider visionai format with multiple sensors.
Run script as below.
``` Python
python visionai_data_format/vai_to_bdd.py -vai_src_folder /Users/yihsuanchen/Downloads/vai_test -bdd_dest_file /Users/yihsuanchen/Downloads/bdd_test4.json -company_code 99 -storage_name ss -container_name dataset -annotation_name groundtruth
``` 
The output bdd json is as below
=> fix(python): convert visionai data to bdd format (considering camera and bbox only)

setup.py, visionai_data_format/schemas/utils/validators.py
remove skipping unwanted existing uuid object under `Frames` that doesn't included in objects under visionai.
[AB#15017](https://dev.azure.com/linkerengineer/Dataverse/_sprints/taskboard/Dataverse%20Team/Dataverse/Sprint%2039%20-%20SAM%20Labeling%20Tool%20(2d%20Semantic%20Segmentation)?workitem=15017)
- skipping unwanted existing uuid object doesn't raise error
- fix skipping assign of unwanted uuid and attributes
- fix raise error message to add listing of error frames ( currently for this error)
we could validate missing dynamic attributes under `Frames` from `Objects`/`Contexts` under `visionai`
- airflow raise error
- listing frames number of error occurred( as mentioned by @JasperSui )
=> fix(python): remove skipping unwanted uuid data

setup.py, tests/test_validators.py, visionai_data_format/schemas/utils/validators.py, visionai_data_format/schemas/visionai_schema.py
add missing `frame_intervals` validation under visionai with `frames` number
[AB#15108](https://dev.azure.com/linkerengineer/Dataverse/_sprints/taskboard/Dataverse%20Team/Dataverse/Sprint%2041%20-%20SAAS%20and%20SAM%20Labeling%20Tool%20(2d%20%EF%BC%86%203d%20Cuboid)?workitem=15108)
- add validation for frames intervals with visionai frames number
- modify test
we could validate wrong `frame_interval` under visionai with its frames number
( `fake_objects_data_single_lidar_wrong_visionai_frame_intervals` is a visionai data with `frame_intervals` and its frames number doesn't match)
=> fix(python): modify frame_intervals under visionai validation

visionai_data_format/schemas/visionai_schema.py
add missing `Frames` validation to avoid none or empty value
[AB#15519](https://dev.azure.com/linkerengineer/Dataverse/_sprints/taskboard/Dataverse%20Team/Dataverse/Sprint%2041%20-%20SAAS%20and%20SAM%20Labeling%20Tool%20(2d%20%EF%BC%86%203d%20Cuboid)?workitem=15519)
- add validation for empty value
- It should work. Could show error for empty frames
=> fix(python): add `Frame` validator to avoid none or empty value

setup.py, tests/test_data/fake_contexts_data.json, tests/test_data/fake_visionai_classification_ontology.json, visionai_data_format/schemas/utils/validators.py
fix parsing static attributes since objects/contexts under visionai could to not contains `object_data` or `context_data`. 
[AB#15681](https://dev.azure.com/linkerengineer/Dataverse/_sprints/taskboard/Dataverse%20Team/Dataverse/Sprint%2042%20-%20SAAS%20and%20SAM%20Labeling%20Tool%20(2d%20%EF%BC%86%203d%20Cuboid)?workitem=15681)
- fix `parse_static_attrs` function to check whether current `objects` or `contexts` under visionai contains `object_data`/`context_data`, since `objects`/`contexts` could to not contains static attributes
- fix `parse_dynamic_attrs` function to remove unused parameter and update comments
- fix tests
it should work. 
- Export dataslice in dataverse could works normally.
- Exported dataslice could be imported normally.
=> fix(python): modify parse static attributes logic

conftest.py, setup.py, tests/test_data/fake_contexts_classification_wrong_vector_value.json, tests/test_data/fake_contexts_data_wrong_vector_value.json, tests/test_validators.py, visionai_data_format/schemas/utils/validators.py, visionai_data_format/utils/converter.py
we fix wrong declaration for `vec` ,  attribute with contains list of data, with `option`.  
Also fix wrong retrieval logic of attributes data.  In previous implementation, we only retrieve data without appending it.
- [AB#15737](https://dev.azure.com/linkerengineer/Dataverse/_sprints/taskboard/Dataverse%20Team/Dataverse/Sprint%2042%20-%20SAAS%20and%20SAM%20Labeling%20Tool%20(2d%20%EF%BC%86%203d%20Cuboid)?workitem=15737)
- change wrong filter logic attribute of `option` type with `vec`. 
- fix `get_frame_object_attr_type` to combine multiple attributes for the same `obj_class` type 
- fix error message to show : class type, attributes which raise error, and the option values
it should work, we could find error inside `contexts` attributes
we also save all of same class type of retrieved …
=> fix(python): fix wrong validation process of attributes info

README.md, setup.py, visionai_data_format/convert_dataset.py, visionai_data_format/converters/__init__.py, visionai_data_format/converters/coco_to_vai.py, visionai_data_format/converters/vai_to_coco.py, visionai_data_format/converters/yolo_to_vai.py, visionai_data_format/schemas/common.py, visionai_data_format/utils/common.py
As title
- [AB#20168](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/20168)
- [AB#19895](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/19895)
- Add YOLO to Visionai converter and adjust the base converter interface
- Refactor coco to visionai (save json outside the base function)
- Little fix for coco image folder name.
- update README
- The converter could work as below
=> feat(python): convert yolo format data to visionai format and little fix for coco <-> visionai

setup.py, visionai_data_format/converters/vai_to_coco.py
- [AB#20515](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/20515)
- image-id is not updated if the frame has not objects.
- update image-id before going the next frame
- Could update the image-id for empty frames
=> fix(python): update image_id for empty frame in vai-to-coco

setup.py, visionai_data_format/converters/vai_to_coco.py
For image with annotations, we should update after annotations are added.
- [AB#20515](https://dev.azure.com/linkerengineer/87361b6b-4b8a-4d65-8243-96cf1163a72f/_workitems/edit/20515)
- Fix update image-id
=> fix(python): update image-id after annotation are added
